In [9]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
%pip install seaborn
import seaborn as sns

Requirement already satisfied: seaborn in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\soura\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [101]:
df = pd.read_csv("ecommerce_sales_analytics_5000.csv")

In [102]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [22]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   str
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), str(4)
memory usage: 468.9 KB

In [24]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='str')

In [25]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [39]:
df['Net_revenue']=(df['quantity']*df['unit_price']*(1-df['discount'])).round(2)

In [40]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Net_revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,468.56

In [44]:
df.drop('Net_revenue',axis=1,inplace=True)

In [111]:
df.shape

(5000, 13)

In [50]:
df['product_category'].unique()

<StringArray>
['Beauty', 'Clothing', 'Electronics', 'Home']
Length: 4, dtype: str

In [51]:
df['region'].unique()

<StringArray>
['South', 'East', 'West', 'North']
Length: 4, dtype: str

In [52]:
df['payment_method'].unique()

<StringArray>
['Wallet', 'Card', 'COD']
Length: 3, dtype: str

In [59]:
df.groupby('product_category')['revenue'].sum().sort_values(ascending=False)

product_category
Electronics    1829899.22
Clothing       1531931.72
Home            982083.92
Beauty          765860.88
Name: revenue, dtype: float64

There not such difference in revenue by region

In [66]:
df.groupby('payment_method')['revenue'].sum().sort_values(ascending=False)

payment_method
Card      2366248.20
COD       1788408.44
Wallet     955119.10
Name: revenue, dtype: float64

More payment are happen using card

In [67]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,rank
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,NaN
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,NaN
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,NaN
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,NaN
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,NaN

In [70]:
df.groupby('product_category')['unit_price'].mean().sort_values(ascending=False).round(2)

product_category
Electronics    314.90
Home           306.26
Beauty         304.71
Clothing       304.01
Name: unit_price, dtype: float64

In [72]:
df.groupby('product_category')['quantity'].mean().sort_values(ascending=False)

product_category
Beauty         4.142462
Home           4.075335
Clothing       4.030699
Electronics    4.000563
Name: quantity, dtype: float64

In [74]:
df.groupby('product_category')['discount'].mean().sort_values(ascending=False)

product_category
Clothing       0.184259
Beauty         0.181425
Home           0.178266
Electronics    0.176652
Name: discount, dtype: float64

In [76]:
df.groupby('product_category')['delivery_days'].mean().sort_values(ascending=False)

product_category
Beauty         6.201936
Home           6.145511
Clothing       6.118877
Electronics    6.070343
Name: delivery_days, dtype: float64

In [78]:
df.groupby('product_category')['order_id'].count().sort_values(ascending=False)

product_category
Electronics    1777
Clothing       1531
Home            969
Beauty          723
Name: order_id, dtype: int64

In [103]:
df.groupby('product_category')['customer_rating'].mean()

product_category
Beauty         3.008990
Clothing       3.005095
Electronics    2.951097
Home           2.940660
Name: customer_rating, dtype: float64

In [104]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [105]:
df['order_date']=pd.to_datetime(df['order_date'])

In [109]:
df['month']=(df['order_date'].dt.month_name())

In [107]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,month
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,January
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,January
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,January
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,January
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74,September
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47,September
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06,September
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38,September
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90,September

In [110]:
df['month'].unique()

<StringArray>
[  'January',  'February',     'March',     'April',       'May',      'June',
      'July',    'August', 'September',   'October',  'November',  'December']
Length: 12, dtype: str

In [113]:
df['order_id'].count()

np.int64(5000)

In [115]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,month
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,January
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,January
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,January
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,January
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,January

In [128]:
grouped_df = (
    df.groupby('region')
    .agg(
        {
            'quantity': 'mean',
            'unit_price': 'mean',
            'discount': 'mean',
            'delivery_days': 'mean',
            'customer_rating': 'mean',
            'revenue': 'sum',
        }
    )
    .sort_values(
        by=['quantity', 'unit_price', 'discount', 'delivery_days', 'customer_rating', 'revenue'],
        ascending=False
    )
)
grouped_df

,quantity,unit_price,discount,delivery_days,customer_rating,revenue
region,,,,,,
West,4.080683,310.600171,0.181241,6.082234,2.961521,1345582.16
North,4.047022,305.104890,0.180016,6.118339,2.993182,1281508.45
South,4.043046,310.252947,0.175513,6.173013,2.967798,1246640.90
East,4.006520,307.767604,0.183032,6.104319,2.973187,1236044.23

In [129]:
grouped_df2 = (
    df.groupby('payment_method')
    .agg(
        {
            'quantity': 'mean',
            'unit_price': 'mean',
            'discount': 'mean',
            'delivery_days': 'mean',
            'customer_rating': 'mean',
            'revenue': 'sum',
        }
    )
    .sort_values(
        by=['quantity', 'unit_price', 'discount', 'delivery_days', 'customer_rating', 'revenue'],
        ascending=False
    )
)
grouped_df2

,quantity,unit_price,discount,delivery_days,customer_rating,revenue
payment_method,,,,,,
Card,4.111454,310.101670,0.181383,6.087225,3.017357,2366248.20
Wallet,4.020921,301.678211,0.173598,6.119247,2.930439,955119.10
COD,3.972379,309.897807,0.181635,6.158963,2.941939,1788408.44

In [130]:
grouped_df3 = (
    df.groupby('month')
    .agg(
        {
            'quantity': 'mean',
            'unit_price': 'mean',
            'discount': 'mean',
            'delivery_days': 'mean',
            'customer_rating': 'mean',
            'revenue': 'sum',
        }
    )
    .sort_values(
        by=['quantity', 'unit_price', 'discount', 'delivery_days', 'customer_rating', 'revenue'],
        ascending=False
    )
)
grouped_df3

,quantity,unit_price,discount,delivery_days,customer_rating,revenue
month,,,,,,
May,4.228111,321.551336,0.191521,6.165899,3.026959,479772.55
November,4.176923,299.984128,0.176179,6.082051,2.947179,410657.88
June,4.171429,306.619333,0.179143,6.126190,2.953333,442941.58
January,4.082949,300.006889,0.189562,6.082949,3.008525,426374.92
October,4.074442,300.713747,0.178635,5.982630,2.984119,407873.12
July,4.032258,309.992281,0.181475,6.248848,2.974424,440570.72
March,4.032258,304.180184,0.180576,6.032258,2.998157,425050.52
August,4.004608,317.171152,0.178410,6.352535,2.938940,460874.78
September,3.987469,313.270952,0.177895,6.223058,2.927318,402368.11
February,3.977215,317.517165,0.171013,5.929114,2.931392,413890.24
April,3.940476,293.844381,0.180167,5.964286,2.957143,398715.16
December,3.818859,315.989752,0.173275,6.215881,3.033747,400686.16

In [132]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,month
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,January
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,January
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,January
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,January
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,January

In [136]:
# Saves the full cleaned dataset to CSV
df.to_csv('clean_dataset_ecommerce.csv', index=False)